CREATE TABLE "user_profiles" (
	"user_id" uuid PRIMARY KEY NOT NULL,
	"weight_kg" numeric(5, 2),
	"height_cm" smallint,
	"age" smallint,
	"biological_sex" text,
	"activity_level" text,
	"tdee_kcal" smallint,
	"goal" text,
	"aggression" text,
	"calorie_target" smallint,
	"protein_target_g" smallint,
	"carbs_target_g" smallint,
	"fat_target_g" smallint,
	"regional_profile" text,
	"oil_usage" text,
	"fat_trim_pork" text,
	"fat_trim_chicken" text,
	"fat_trim_fish" text,
	"bone_awareness" boolean DEFAULT false,
	"default_rice_portion" text,
	"sugar_braised" text,
	"bowl_size_ml" smallint DEFAULT 200,
	"plate_size_ml" smallint DEFAULT 400,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "user_profiles_biological_sex_check" CHECK ("user_profiles"."biological_sex" IN ('male', 'female')),
	CONSTRAINT "user_profiles_activity_level_check" CHECK ("user_profiles"."activity_level" IN ('sedentary', 'light', 'moderate', 'very_active')),
	CONSTRAINT "user_profiles_goal_check" CHECK ("user_profiles"."goal" IN ('cutting', 'bulking', 'maintaining')),
	CONSTRAINT "user_profiles_aggression_check" CHECK ("user_profiles"."aggression" IN ('gentle', 'moderate', 'aggressive')),
	CONSTRAINT "user_profiles_regional_profile_check" CHECK ("user_profiles"."regional_profile" IN ('mien_bac', 'mien_trung', 'mien_nam', 'mien_tay')),
	CONSTRAINT "user_profiles_oil_usage_check" CHECK ("user_profiles"."oil_usage" IN ('minimal', 'normal', 'heavy')),
	CONSTRAINT "user_profiles_fat_trim_pork_check" CHECK ("user_profiles"."fat_trim_pork" IN ('trim', 'eat_all', 'by_dish')),
	CONSTRAINT "user_profiles_fat_trim_chicken_check" CHECK ("user_profiles"."fat_trim_chicken" IN ('trim', 'eat_all', 'by_dish')),
	CONSTRAINT "user_profiles_fat_trim_fish_check" CHECK ("user_profiles"."fat_trim_fish" IN ('trim', 'eat_all', 'by_dish')),
	CONSTRAINT "user_profiles_default_rice_portion_check" CHECK ("user_profiles"."default_rice_portion" IN ('small', 'medium', 'large')),
	CONSTRAINT "user_profiles_sugar_braised_check" CHECK ("user_profiles"."sugar_braised" IN ('low', 'medium', 'high'))
);
--> statement-breakpoint
ALTER TABLE "user_profiles" ADD CONSTRAINT "user_profiles_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE cascade ON UPDATE no action;