CREATE TABLE "vietnamese_food_composition" (
	"id" text PRIMARY KEY NOT NULL,
	"name_primary" text NOT NULL,
	"name_alt" text[],
	"name_en" text NOT NULL,
	"type_vn" text NOT NULL,
	"type_en" text NOT NULL,
	"source" text DEFAULT 'FAO_VN_2007' NOT NULL,
	"state" text NOT NULL,
	"inedible_portion_pct" numeric,
	"calories_kcal" numeric,
	"protein_g" numeric,
	"carbohydrate_g" numeric,
	"fat_g" numeric,
	"fiber_g" numeric,
	"sodium_mg" numeric,
	"calcium_mg" numeric,
	"iron_mg" numeric,
	"magnesium_mg" numeric,
	"phosphorus_mg" numeric,
	"potassium_mg" numeric,
	"zinc_mg" numeric,
	"copper_mcg" numeric,
	"manganese_mg" numeric,
	"beta_carotene_mcg" numeric,
	"vitamin_a_mcg" numeric,
	"vitamin_d_mcg" numeric,
	"vitamin_e_mg" numeric,
	"vitamin_k_mcg" numeric,
	"vitamin_c_mg" numeric,
	"vitamin_b1_mg" numeric,
	"vitamin_b2_mg" numeric,
	"vitamin_pp_mg" numeric,
	"vitamin_b5_mg" numeric,
	"vitamin_b6_mg" numeric,
	"vitamin_b9_mcg" numeric,
	"vitamin_b12_mcg" numeric,
	"vitamin_h_mcg" numeric,
	"last_verified" date,
	CONSTRAINT "vietnamese_food_composition_state_check" CHECK ("vietnamese_food_composition"."state" IN ('raw', 'cooked'))
);
